version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build
            - run: npm test
            - codecov/upload:
                file: {{ coverage_report_filepath }}
workflows:
  build-and-test:
    jobs:
      - build-and-test
