version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build --cov-report xml --cov-report term --cov .
            - run: npm test --cov-report xml --cov-report term --cov .
            - run: bash <(curl -s https://codecov.io/bash) -Z
workflows:
  build-and-test:
    jobs:
      - build-and-test
